export default [
  {
    id: 0,
    title: 'All Day Event very long title',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 12, 0),
    end: new Date(2018, 12, 0),
  },
  {
    id: 1,
    title: 'Long Event',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 12, 7),
    end: new Date(2018, 12, 7),
  },

  {
    id: 2,
    title: 'DTS STARTS',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2016, 2, 13, 0, 0, 0),
    end: new Date(2016, 2, 13, 0, 0, 0),
  },

  {
    id: 3,
    title: 'DTS ENDS',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2016, 10, 6, 0, 0, 0),
    end: new Date(2016, 10, 6, 0, 0, 0),
  },

  {
    id: 4,
    title: 'Some Event',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 11, 9, 0, 0, 0),
    end: new Date(2018, 11, 9, 0, 0, 0),
  },
  {
    id: 5,
    title: 'Conference',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 11, 11),
    end: new Date(2018, 11, 11),
    desc: 'Big conference for important people',
  },
  {
    id: 6,
    title: 'Meeting',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 11, 12, 10, 30, 0, 0),
    end: new Date(2018, 11, 12, 10, 30, 0, 0),
    desc: 'Pre-meeting meeting, to prepare for the meeting',
  },
  {
    id: 7,
    title: 'Lunch',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 11, 12, 12, 0, 0, 0),
    end: new Date(2018, 11, 12, 12, 0, 0, 0),
    desc: 'Power lunch',
  },
  {
    id: 8,
    title: 'Meeting',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 11, 12, 14, 0, 0, 0),
    end: new Date(2018, 11, 12, 14, 0, 0, 0),
  },
  {
    id: 9,
    title: 'Happy Hour',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 11, 12, 17, 0, 0, 0),
    end: new Date(2018, 11, 12, 17, 30, 0, 0),
    desc: 'Most important meal of the day',
  },
  {
    id: 10,
    title: 'Dinner',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 12, 12, 20, 0, 0, 0),
    end: new Date(2018, 12, 12, 20, 0, 0, 0),
  },
  {
    id: 11,
    title: 'Birthday Party',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 11, 13, 7, 0, 0),
    end: new Date(2018, 11, 13, 7, 30, 0),
  },
  {
    id: 11.9,
    title: 'Late Night Event',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 11, 17, 19, 30, 0),
    end: new Date(2018, 11, 17, 2, 0, 0),
  },
  {
    id: 12.5,
    title: 'Late Same Night Event',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 11, 17, 19, 30, 0),
    end: new Date(2018, 11, 17, 23, 30, 0),
  },
  {
    id: 13,
    title: 'Multi-day Event',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(2018, 11, 20, 19, 30, 0),
    end: new Date(2018, 11, 20, 2, 0, 0),
  },
  {
    id: 14,
    title:
      "Sean, we can't wait to get you on campus this weekend for your official",
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(new Date().setHours(new Date().getHours() - 3)),
    end: new Date(new Date().setHours(new Date().getHours() - 3)),
  },
  {
    id: 15,
    title:
      "Sean, we can't wait to get you on campus this weekend for your official",
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(new Date().setHours(new Date().getHours() - 3)),
    end: new Date(new Date().setHours(new Date().getHours() - 3)),
  },
  {
    id: 16,
    title:
      "Sean, we can't wait to get you on campus this weekend for your official",
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(new Date().setHours(new Date().getHours() - 4)),
    end: new Date(new Date().setHours(new Date().getHours() - 4)),
  },
  {
    id: 17,
    title:
      "Sean, we can't wait to get you on campus this weekend for your official",
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(new Date().setHours(new Date().getHours() - 6)),
    end: new Date(new Date().setHours(new Date().getHours() - 5)),
  },
  {
    id: 18,
    title:
      "Sean, we can't wait to get you on campus this weekend for your official",
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(new Date().setHours(new Date().getHours() - 7)),
    end: new Date(new Date().setHours(new Date().getHours() - 6)),
  },
  {
    id: 19,
    title: 'Today',
    image: 'https://i.imgur.com/88Sshnn.jpg',
    start: new Date(new Date().setHours(new Date().getHours() - 8)),
    end: new Date(new Date().setHours(new Date().getHours() - 7)),
  },
  // {
  //   id: 20,
  //   title: 'Today',
  //   image: 'https://i.imgur.com/88Sshnn.jpg',
  //   start: new Date(new Date().setHours(new Date().getHours() - 9)),
  //   end: new Date(new Date().setHours(new Date().getHours() - 8)),
  // },
]
